server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: image-hosting
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: moe.imtop1.imagehosting.common.entity
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: true
      logic-not-delete-value: false


sa-token:
  jwt-secret-key: 3fc0449993ee6dc5e66ccd9658d3c33a