server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: image-hosting
  profiles:
#    active: dev
    active: dev-local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mail:
    host: smtp.qq.com
    port: 587
    username: vsjun8@qq.com
    password: wonwyytuummihhdg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    template-loader-path:  classpath:/templates/
    suffix: .ftl
    charset: UTF-8


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: moe.imtop1.imagehosting.images.domain,moe.imtop1.imagehosting.system.domain
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: true
      logic-not-delete-value: false


sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  is-log: true
  jwt-secret-key: 3fc0449993ee6dc5e66ccd9658d3c33a