spring:
  datasource:
    url: jdbc:postgresql://101.132.141.214:15432/image
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      database: 3
  mail:
    host: smtp.qq.com
    port: 587
    username: vsjun8@qq.com
    password: wonwyytuummihhdg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true