server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    database: 0
    timeout: 10000

# MinIO配置
minio:
  endpoint: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ACCESSKEY}
  secretKey: ${MINIO_SECRETKEY}
  bucketName: ${MINIO_BUCKETNAME}
  publicUrl: ${MINIO_PUBLICURL}